Add filtering page to black list projects in main view
TheRedDot/MergeRequestsCI pull request #2
Opened 2019-04-09 15:50 UTC by TomBerriot

#### Description

Add a new system to filter out projects from the dashboard.
It adds a new page called "Filtering" which shows current projects of the gitlab server.
These projects can be switched on or off to be filtered from the dashboard page.
The selected filtered ("blacklisted") projects are then stored in the localStorage of the client.

#### Resume

* Bug fix: no
* New feature: yes

2019-04-10 09:19 UTC, nclsHart requested changes
We should consolidate our eslint config 🤔.

2019-04-10 09:19 UTC, nclsHart commented on .gitignore
> +.idea
This should belongs to your gitignore global.

2019-04-10 09:19 UTC, nclsHart commented on app/js/controllers/dashboard.js
> +      vm.mergeRequests = mergeRequests.filter(function (mergeRequest){
Missing space before block.

2019-04-10 09:19 UTC, nclsHart commented on app/js/controllers/filtering.js
> +  vm.toggleBlackList = function(project){
Missing space before block.

2019-04-10 09:19 UTC, nclsHart commented on app/js/controllers/filtering.js
> +    if(indexOfProject !== -1){
Missing space before block.

2019-04-10 09:19 UTC, nclsHart commented on app/js/controllers/filtering.js
> +    }else {
Missing space before keyword.

2019-04-10 09:19 UTC, nclsHart commented on app/js/controllers/filtering.js
> +  ProjectsFetcher.getProjects().then(function(projects){
Missing space before block.

2019-04-10 09:19 UTC, nclsHart commented on app/js/services/projects_fetcher.js
> +  function formatProjectList(projects){
Missing space before block.

2019-04-10 09:19 UTC, nclsHart commented on app/js/services/projects_fetcher.js
> +    return projects.map(function(project){
Missing space before block.

2019-04-10 09:19 UTC, nclsHart commented on app/js/services/projects_fetcher.js
> +      if(blackListedProjectsIds.indexOf(project.id) !== -1){
Missing space before block.

2019-04-14 08:27 UTC, notFloran commented
It bothers me a bit of merged knowing that the project is in maintenance mode and that a re-write has begin, see https://github.com/TheGrowingPlant/gitlab-reviewer

2019-04-14 13:32 UTC, closed without merging